digest: fix SRI section ref
httpwg/http-extensions pull request #1354
Opened 2020-12-29 20:40 UTC by LPardue

2020-12-29 21:50 UTC, reschke requested changes
But that section doesn't even "identity" or content codings; it seems more context is needed.

2020-12-29 23:05 UTC, LPardue commented
Ha, Touche! The actual piece I want to reference is **section 3.3.5** - https://www.w3.org/TR/2016/REC-SRI-20160623/#does-response-match-metadatalist

This says:

```
This algorithm allows the user agent to accept multiple, valid strong hash functions. For example, a developer might write a script element such as:
Example 7

<script src="https://example.com/example-framework.js"
        integrity="sha384-Li9vy3DqF8tnTXuiaAJuML3ky+er10rcgNR/VqsVpcw+ThHmYcwiB1pbOxEbzJr7
                   sha384-+/M6kredJcxdsqkczBUjMLvqyHb1K/JThDXWsBVxMEeZHEaMKEOEct339VItX1zB"
        crossorigin="anonymous"></script>

which would allow the user agent to accept two different content payloads, one of which matches the first SHA384 hash value and the other matches the second SHA384 hash value.
```

Given this, do you think the current Digest text and section reference is enough, or is there more that I could say here?

2020-12-30 05:14 UTC, reschke commented
That section talks about different representations in general, not specifically about content codings, right? As such I find that piece of text still very confusing.

2021-01-14 19:21 UTC, LPardue commented
This PR needs work to address Julian's points. I intend to get to this in the near future.

2021-01-15 11:25 UTC, ioggstream commented on draft-ietf-httpbis-digest-headers.md
> +The SRI digest value is calculated over the representation data of a resource
Fix 1: The correct terminology is `without any content-coding applied`, as "identity" is not a content-coding. https://github.com/httpwg/http-core/pull/389

2021-01-15 11:26 UTC, ioggstream commented on draft-ietf-httpbis-digest-headers.md
> +Section 3.3.5 of [SRI] describes the benefit of not applying content-codings:
Fix 2: reference the section from https://github.com/httpwg/http-extensions/pull/1354#issuecomment-752270667

2021-01-15 11:27 UTC, ioggstream commented on draft-ietf-httpbis-digest-headers.md
> +thus protecting different representations of a given resource. However, this is different
Fix 3: if it's the same url, then it's the same resource, which may have different representation => different representation data (eg. content-language, content-encoding, ...)

2021-01-15 11:30 UTC, ioggstream commented
@LPardue reading https://github.com/w3c/webappsec-subresource-integrity/blob/master/index.bs#L353 I am still not sure whether `SRI` *always* ignore content-codings... it seems at a minimum confusing to me.

2021-02-04 14:50 UTC, ioggstream commented
@reschke I read SRI and it seems unclear whether it is content-coding aware or not (see comment above https://github.com/httpwg/http-extensions/pull/1354#issuecomment-760888084).

I tried to address all your concerns on SRI here. Feel free to amend, otherwise.

2021-04-13 14:14 UTC, reschke approved these changes

2021-04-13 14:16 UTC, merged