Fairness scheduling across clients is an operator choice
httpwg/http-extensions pull request #1821
Opened 2021-12-06 19:36 UTC by LPardue

closes #1820﻿

2021-12-06 20:07 UTC, kazuho approved these changes

2021-12-06 20:51 UTC, kazuho reviewed
I take back my approval, please see https://github.com/httpwg/http-extensions/issues/1820#issuecomment-987196961.

2021-12-06 20:52 UTC, kazuho requested changes
I take back my approval, please see https://github.com/httpwg/http-extensions/issues/1820#issuecomment-987196961.

2021-12-07 00:37 UTC, closed without merging

2021-12-07 00:37 UTC, LPardue commented
closed in favour of #1825