Fix: #1837. Mention collisions.
httpwg/http-extensions pull request #1853
Opened 2021-12-13 10:32 UTC by ioggstream

## This PR

Fix: #1837. Mention collisions.

2021-12-21 14:01 UTC, jricher requested changes
As mentioned in the linked issue, this PR is not complete: there needs to be a discussion of collisions and, more broadly, algorithm selection in the security considerations, since this draft leaves the choice of which algorithms to accept entirely up to the implementor. I would also expect to see a discussion of the danger of a receiver of Digest headers blindly accepting "all" algorithms defined in the draft or registry, even if they aren't deprecated. For example, a system in which all "good" clients use SHA512 but still accepts SHA256 is only really protected by SHA256 since that's the lightest weight item an attacker can make use of.

2022-02-16 16:41 UTC, ioggstream commented
@martinthomson WDYT?

2022-02-16 23:59 UTC, martinthomson commented
If you are talking about the standard assumptions about what a cryptographic hash function provides, you need to talk about what properties you are getting (or, conversely, what the not-secure options don't provide).  So not just collisions, but first- and second-preimage resistance.

Justin also points out that you need to consider the target security level in making any recommendation.  As in, it might be that a 256-bit hash suffices in some cases, but not others.  I think that is secondary to what I think we need to be saying here, but it's probably worth including something.

> The "standard" algorithms listed in this document are suitable for many purposes, including adversarial situations where hash functions might need to provide resistance to collision, first-preimage and second-preimage attacks.  Algorithms listed as "insecure" either provide none of these properties, or are known to be weak (see {{NO-MD5}} and {{NO-SHA1}}).
>
> For adversarial situations, which of the "standard" algorithms are acceptable will depend on the level of protection the circumstances demand. As there is no negotiation, endpoints that depend on a (digest|hash) for security will be vulnerable to attacks on the weakest algorithm they are willing to accept.

2022-02-17 09:41 UTC, ioggstream commented
Thanks @martinthomson! @jricher can you PTAL?

2022-02-17 17:07 UTC, LPardue approved these changes
LGTM, thank you all!

2022-02-17 17:09 UTC, LPardue commented on draft-ietf-httpbis-digest-headers.md
> +or are known to be weak (see {{NO-MD5}} and {{NO-SHA1}}).
```suggestion
or are known to be weak (see {{NO-MD5}} and {{NO-SHA}}).
```

ref typo causing build failure

2022-02-17 17:16 UTC, LPardue commented
apologies, the ref is `NO-SHA` in main. I changed that to avoid table width alignment problems. if you rebase, it should work. If you need to rename `NO-SHA` to `NO-SHA1` that is fine too.

2022-02-18 09:53 UTC, merged