client-cert-field: update refs to now RFCs 9110/9114/9204
httpwg/http-extensions pull request #2256
Opened 2022-10-03 17:07 UTC by bc-pi

update refs for HTTP Semantics, HTTP/3, and QPACK to point to the now RFCs 9110/9114/9204

for #2146

2022-10-06 18:08 UTC, MikeBishop requested changes
HTTP/2 should be RFC9113 now, and these should use the display names in [the style guide](https://github.com/httpwg/admin/blob/main/editors/style-guide.md). #2263 has these changes, since that was easier than using the "suggestions" option in the review.

2022-10-06 22:48 UTC, b---c commented
Thanks Mike. That was much easier than using the "suggestions" option. I merged #2263 and then fixed(!?) the YAML header with [79c8b49](https://github.com/httpwg/http-extensions/pull/2256/commits/79c8b493831c83dc4aa78401fd415db1413b1161). I think this one is good to go now?

2022-10-10 19:41 UTC, MikeBishop approved these changes

2022-10-10 19:42 UTC, MikeBishop commented
Yes, good to go!

2022-10-10 19:45 UTC, merged