Refine requirement for failure
httpwg/http-extensions pull request #2404
Opened 2023-02-07 04:39 UTC by mnot

Fixes #2399

2023-02-07 05:09 UTC, reschke requested changes
That's a breaking change from 8941 which essentially ends draconian error handling.

2023-02-07 05:43 UTC, mnot commented
... or it's a clarification that aligns the text in the two different sections. Sounds like we should discuss on list.

2023-02-28 06:04 UTC, mnot commented on draft-ietf-httpbis-sfbis.md
> +If parsing fails -- including when calling another algorithm -- the entire field value MUST be ignored (i.e., treated as if the field were not present in the section), unless the field definition spe
```suggestion
If parsing fails -- including when calling another algorithm -- either the entire field value MUST be ignored (i.e., treated as if the field were not present in the section), or alternatively the complete HTTP message MUST be treated as malformed. This is intentionally strict to improve interoperability and safety, and field specifications that use Structured Fields are not allowed to loosen this requirement.
```

2023-02-28 06:38 UTC, reschke requested changes

2023-02-28 06:38 UTC, reschke commented on draft-ietf-httpbis-sfbis.md
> +If parsing fails -- including when calling another algorithm -- either the entire field value MUST be ignored (i.e., treated as if the field were not present in the section), or alternatively the com
I still think that the "..,including when..." needs tuning; will make a proposal later today.

2023-03-01 08:03 UTC, bsdphk commented
I still dont understand why we have some of the "strict" stuff in 1.1 and some in 4.2.

I would move the paragraph from 4.2 to 1.1 to improve the chance people actually read it.

2023-03-03 00:32 UTC, mnot commented
Disagree; implementers are more likely to look at the parsing section, not what they perceive as boilerplate at the top. 1.1 covers the philosophy and general approach; 4.2 talks about the implementation details.

2023-03-03 07:34 UTC, bsdphk commented
"This is intentionally strict […]" sounded philosophical to me, but whatever :-)

2023-03-06 05:11 UTC, merged